/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "rnnoise.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* Header for class com_kgeapp_rnnoise_RNNoise */
#define FRAME_SIZE 480
#ifndef _Included_com_kgeapp_rnnoise_RNNoise
#define _Included_com_kgeapp_rnnoise_RNNoise
#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned char byte;
/*
 * Class:     com_kgeapp_rnnoise_RNNoise
 * Method:    cancelNoise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kgeapp_rnnoise_RNNoise_cancelNoise(JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jbyteArray JNICALL Java_com_kgeapp_rnnoise_RNNoise_flowRNNoise(JNIEnv *, jobject, jbyteArray);

//char* Jstring2CStr(JNIEnv* env, jstring jstr);

#ifdef __cplusplus
}
#endif
#endif
