/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kgeapp_aecm_jni_AECM */

#ifndef _Included_com_kgeapp_aecm_jni_AECM
#define _Included_com_kgeapp_aecm_jni_AECM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kgeapp_aecm_jni_AECM
 * Method:    runAECM
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kgeapp_aecm_jni_AECM_runAECM
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
