/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kgeapp_sox_jni_sox */

#ifndef _Included_com_kgeapp_sox_jni_sox
#define _Included_com_kgeapp_sox_jni_sox
#ifdef __cplusplus
extern "C" {
#endif



// char* DtoS(double d){
//   char str[10];
//   sprintf(str,"%.1lf",d);
//   return str;
// }
//   //c-function string->double
// double StoD(char* str){
//   double dd;
//   sscanf(str,"%lf",&dd);
//   return dd;
// }



/*
 * Class:     com_kgeapp_sox_jni_sox
 * Method:    nativeInit
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_kgeapp_sox_jni_sox_nativeInit
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_kgeapp_sox_jni_sox
 * Method:    nativeAddVolEffect
 * Signature: (JI)V
 */
JNIEXPORT jint JNICALL Java_com_kgeapp_sox_jni_sox_nativeAddVolEffect
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_kgeapp_sox_jni_sox
 * Method:    nativeAddFlangerEffect
 * Signature: (J)V
 */
JNIEXPORT jint JNICALL Java_com_kgeapp_sox_jni_sox_nativeAddFlangerEffect
  (JNIEnv *, jclass);

/*
 * Class:     com_kgeapp_sox_jni_sox
 * Method:    nativeAddEqualizerEffect
 * Signature: (JIDD)V
 */
JNIEXPORT jint JNICALL Java_com_kgeapp_sox_jni_sox_nativeAddEqualizerEffect
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     com_kgeapp_sox_jni_sox
 * Method:    nativeAddHighPassEffect
 * Signature: (JID)V
 */
JNIEXPORT jint JNICALL Java_com_kgeapp_sox_jni_sox_nativeAddHighPassEffect
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     com_kgeapp_sox_jni_sox
 * Method:    nativeAddLowPassEffect
 * Signature: (JID)V
 */
JNIEXPORT jint JNICALL Java_com_kgeapp_sox_jni_sox_nativeAddLowPassEffect
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     com_kgeapp_sox_jni_sox
 * Method:    nativeAddCompandEffect
 * Signature: (J)V
 */
JNIEXPORT jint JNICALL Java_com_kgeapp_sox_jni_sox_nativeAddCompandEffect
  (JNIEnv *, jclass);

/*
 * Class:     com_kgeapp_sox_jni_sox
 * Method:    nativeAddReverbEffect
 * Signature: (JZIIIIII)V
 */
JNIEXPORT jint JNICALL Java_com_kgeapp_sox_jni_sox_nativeAddReverbEffect
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_kgeapp_sox_jni_sox
 * Method:    nativeAddChorusEffects
 * Signature: (J)V
 */
JNIEXPORT jint JNICALL Java_com_kgeapp_sox_jni_sox_nativeAddChorusEffects
  (JNIEnv *, jclass);

/*
 * Class:     com_kgeapp_sox_jni_sox
 * Method:    nativeAddEchoEffects
 * Signature: (J)V
 */
JNIEXPORT jint JNICALL Java_com_kgeapp_sox_jni_sox_nativeAddEchoEffects
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_kgeapp_sox_jni_sox
 * Method:    nativeFlowEffects
 * Signature: (J)V
 */
JNIEXPORT jint JNICALL Java_com_kgeapp_sox_jni_sox_nativeFlowEffects
  (JNIEnv *, jclass);



#ifdef __cplusplus
}
#endif
#endif
